name: Build and Package React Library

on:
  workflow_dispatch: # 允许手动触发
  push:
    branches: [ master ]
    paths:
      - 'packages/platforms/react/**' # 仅当react目录变更时触发

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/platforms/react # 设置工作目录

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # 根据项目需求选择版本
          # cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build

      - name: Generate type definitions
        run: npm run tsc

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: relation-graph-react-package
          path: |
            packages/platforms/react/dist/
            packages/platforms/react/types/
          retention-days: 7
